apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::794334498024:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H3C5VJG48637
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::794334498024:role/UdacityFlaskDeployCBKubectlRole
      username: build       
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-17T02:24:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1619"
  uid: 09589f0a-fbf5-44a3-b858-dfdb3ae986d8
