apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::044014125566:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::044014125566:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RWAANDUWQ593
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-03T16:58:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1586"
  uid: 5680b95f-e321-45e1-b427-b8e81f2ebd43
